#!/bin/sh
# fbsetbg -C ~/Docs/backgrounds/Fluxbox-logo.png
xmodmap "/home/serg/.Xmodmap"
play ~/Docs/sounds/desktop-login.ogg &
# lxpanelx &
fbpanel &
numlockx &
unclutter -idle 2 &
parcellite &
xbindkeys &
fbsetbg -f ~/Docs/backgrounds/default.jpg
idesk &
conky &
udiskie --tray &
# dbus-launch nm-applet &
~/bin/urxvt-run.sh &
# ~/bin/firefox &
/opt/firefox/firefox &
# google-chrome-beta &
KeeWeb &
# keepassx &
# goldendict &
# sdcv &
exec /usr/bin/fluxbox -log "/home/serg/.fluxbox/log"
