#!/bin/sh
xmodmap "/home/serg/.Xmodmap" &
nvidia-settings --load-config-only &
play ~/Docs/sounds/desktop-login.ogg &
# lxpanelx &
fbpanel &
numlockx &
unclutter -idle 2 &
parcellite &
xbindkeys &
fbsetbg -f ~/Docs/backgrounds/1920x1080/default.jpg
idesk &
conky &
udiskie --tray &
# dbus-launch nm-applet &
# ~/bin/urxvt-run.sh &
tilda &
# ~/bin/firefox &
# /opt/firefox/firefox &
# google-chrome-beta &
KeeWeb &
# keepassx &
# goldendict &
# sdcv &
exec /usr/bin/fluxbox -log "/home/serg/.fluxbox/log"
