" Size of GVim window
set lines=35 columns=99

" Don't display the menu or toolbar. Just the screen.
"set guioptions-=m
set guioptions-=T

" Font. Very important.
if has('win32') || has('win64')
	" set guifont=Monaco:h16
	" http://jeffmilner.com/index.php/2005/07/30/windows-vista-fonts-now-available/
	set guifont=Consolas:h12:cANSI
elseif has('unix')
	let &guifont="Monospace 10"
endif

set go-=T                       " hide the toolbar
set go-=m                       " hide the menu
" The next two lines are quite tricky, but in Gvim, if you don't do this, if you
" only hide all the scrollbars, the vertical scrollbar is showed anyway
"set go+=rRlLbh                  " show all the scrollbars
set go-=rRlLbh                  " hide all the scrollbars
