# /etc/skel/.bash_profile
export WINEARCH="win32"
# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
#[[ -f ~/.bashrc ]] && . ~/.bashrc
